### ISSUE TITLE
Regarding The Class Notes

### ISSUE THREAD

**Issue by safdarkb** [AmanRelan/Fullstack-Cohort-0to100#16]
Hi, 

First of all thanks for the provided notes of the 0-100x cohort  .

Notes  and codes untill week 3 is completed.

week 4 notes are not added. 

I have no authority to ask you for the notes,  but it will be very helpfull for many beginners like me. 

if you get time and if possible, please continue the effort for the complete course .

thanks again in advance

**Comment by AmanRelan** [comment]
I was busy solving the assignments before I begin week-4 classes. Will be uploading them soon.

**Comment by safdarkb** [comment]
ok.   thank you
